version: '3.3'

services:
  nexus:
    image: sonatype/nexus3:3.6.0
    ports: [ "8081:8081", "8082:8082" ]
    volumes:
    - nexus-data:/nexus-data

  gitlab:
    image: gitlab/gitlab-ce:8.5.8-ce.0
    ports: [ "8180:80", "8122:22" ]
    volumes:
    - gitlab-conf:/etc/gitlab
    - gitlab-log:/var/log/gitlab
    - gitlab-data:/var/opt/gitlab
    environment:
    - GITLAB_ROOT_PASSWORD=aqwzsx12341

  jenkins:
    image: treeptik/jenkins:2.89-alpine
    ports: [ "8280:8080" ]
    volumes:
    - jenkins:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    - ./config.json:/var/jenkins_home/.docker/config.json

volumes:
  nexus-data:
  gitlab-conf:
  gitlab-log:
  gitlab-data:
  jenkins:

